// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicDiary.Data;

#nullable disable

namespace MusicDiary.Data.Migrations
{
    [DbContext(typeof(DiaryDbContext))]
    [Migration("20260912151005_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("MusicDiary.Models.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ListeningDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Review")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("Albums", t =>
                        {
                            t.HasCheckConstraint("CK_Album_Artist", "length(trim(Artist)) BETWEEN 1 AND 200");

                            t.HasCheckConstraint("CK_Album_Rating", "Rating IS NULL OR Rating BETWEEN 1 AND 10");

                            t.HasCheckConstraint("CK_Album_Status", "Status IN (0, 1, 2)");

                            t.HasCheckConstraint("CK_Album_Title", "length(trim(Title)) BETWEEN 1 AND 200");

                            t.HasCheckConstraint("CK_Album_Year", "ReleaseYear BETWEEN 1000 AND 9999");
                        });
                });

            modelBuilder.Entity("MusicDiary.Models.ListeningSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlbumId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ListenedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("ListenedAt");

                    b.ToTable("ListeningSessions");
                });

            modelBuilder.Entity("MusicDiary.Models.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlbumId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("Tracks", t =>
                        {
                            t.HasCheckConstraint("CK_Track_Title", "length(trim(Title)) BETWEEN 1 AND 200");
                        });
                });

            modelBuilder.Entity("MusicDiary.Models.ListeningSession", b =>
                {
                    b.HasOne("MusicDiary.Models.Album", null)
                        .WithMany("ListeningSessions")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MusicDiary.Models.Track", b =>
                {
                    b.HasOne("MusicDiary.Models.Album", null)
                        .WithMany("Tracks")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MusicDiary.Models.Album", b =>
                {
                    b.Navigation("ListeningSessions");

                    b.Navigation("Tracks");
                });
#pragma warning restore 612, 618
        }
    }
}
